project_name: pathman

before:
  hooks:
    - go mod tidy

builds:
  - id: pathman
    binary: pathman
    main: ./cmd/pathman
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/sfkleach/pathman/pkg/commands.Version={{.Version}}
      - -X github.com/sfkleach/pathman/pkg/commands.Source=https://github.com/sfkleach/pathman

archives:
  - id: pathman-archive
    format: tar.gz
    name_template: "pathman_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*
      - docs/**/*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: '^feat.*:.*'
      order: 0
    - title: 'Bug fixes'
      regexp: '^fix.*:.*'
      order: 1
    - title: 'Other Changes'
      order: 999

release:
  github:
    owner: sfkleach
    name: pathman
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} {{.Version}}"
